### ISSUE TITLE
Data Needed objects failing - 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by squ1ddy** [atc-project/atomic-threat-coverage#153]
Hello,

Receiving this error every time the `docker run -it atc' command is run for each DN object:

```
Err message: 'NoneType' object is not iterable
------------------------------------------------------------
Traceback (most recent call last):
  File "/app/scripts/populatemarkdown.py", line 240, in data_needed
    dn.render_template("markdown")
  File "/app/scripts/dataneeded.py", line 160, in render_template
    self.content = template.render(self.dn_fields)
  File "/usr/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "templates/markdown_dataneeded_template.md.j2", line 5, in <module>
    | Mitigation Policy | <ul>{% for mpolicy in mitigation_policy %}<li>{% if mpolicy != "None" %}[{{ mpolicy }}](../Mitigation_Policies/{{mpolicy}}.md){% else %} Not existing {% endif %}</li>{% endfor %}</ul> |
TypeError: 'NoneType' object is not iterable
------------------------------------------------------------
../data_needed/DN_0093_linux_clamav_log.yml failed

'NoneType' object is not iterable
```

Would appreciated somebody pointing me in the right direction for how to fix. 

Thanks in advance,

squ1ddy

**Comment by squ1ddy** [comment]
Don't really know how to troubleshoot this properly but had a look at the file templates/markdown_dataneeded_template.md.j2 on Line 5 and noticed that the **mitigation_policy** has an '_' where as on Line 4 **loggingpolicy** does not. So I removed the underscore and no longer get the error.

Before:

```
| Logging Policy    | <ul>{% for policy in loggingpolicy %}<li>{% if policy != "None" %}[{{ policy }}](../Logging_Policies/{{policy}}.md){% else %} Not existing {% endif %}</li>{% endfor %}</ul> |
| Mitigation Policy | <ul>{% for mpolicy in mitigation_policy %}<li>{% if mpolicy != "None" %}[{{ mpolicy }}](../Mitigation_Policies/{{mpolicy}}.md){% else %} Not existing {% endif %}</li>{% endfor %}</ul> |
```

After:

```
| Logging Policy    | <ul>{% for policy in loggingpolicy %}<li>{% if policy != "None" %}[{{ policy }}](../Logging_Policies/{{policy}}.md){% else %} Not existing {% endif %}</li>{% endfor %}</ul> |
| Mitigation Policy | <ul>{% for mpolicy in mitigationpolicy %}<li>{% if mpolicy != "None" %}[{{ mpolicy }}](../Mitigation_Policies/{{mpolicy}}.md){% else %} Not existing {% endif %}</li>{% endfor %}</ul> |
```

I'll do a bit of further testing and then figure out how to commit this to project.

**Comment by squ1ddy** [comment]
Looks like @sn0w0tter was working on this during this commit [https://github.com/atc-project/atomic-threat-coverage/pull/151/commits/d2262f0730ab0fc5f9738bff482dc5fea1ab574e](url)

**Comment by yugoslavskiy** [comment]
Thank you for describing the issue, @squ1ddy! we've fixed it.
