### ISSUE TITLE
Fix issues for Customers population

### ISSUE THREAD

**Issue by yugoslavskiy** [atc-project/atomic-threat-coverage#170]
Populating Customers..
../customers/CU_0001_TESTCUSTOMER.yml failed

'NoneType' object is not subscriptable

```
Err message: 'NoneType' object is not subscriptable
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yugoslavskiy/Dropbox/projects/atomic-threat-coverage/scripts/populatemarkdown.py", line 363, in customer
    cu.render_template("markdown")
  File "/Users/yugoslavskiy/Dropbox/projects/atomic-threat-coverage/scripts/customer.py", line 109, in render_template
    name = rules_by_title.get(title)[1]
TypeError: 'NoneType' object is not subscriptable
------------------------------------------------------------
```

**Comment by yugoslavskiy** [comment]
the issue was caused by a wrong Sigma Rule name mentioned in the list. Most probably the name has been changed or the rule has been deleted due to OSCD or other activities.
