### ISSUE TITLE
Creating ATC root page

### ISSUE THREAD

**Issue by bambukuning** [atc-project/atomic-threat-coverage#232]
Login: *********
Password: 
[+] ATT&CK mapping has been updated
[*] Creating ATC root page...
Traceback (most recent call last):
  File "/app/main.py", line 152, in <module>
    DataPopulateConfluence(auth=auth, auto=args.auto, lp=args.loggingpolicy,
  File "/app/data/atc_data/scripts/populateconfluence.py", line 49, in __init__
    if init_main(self.auth):
  File "/app/data/atc_data/scripts/init_confluence.py", line 48, in main
    if not DATAutils.push_to_confluence(data, url, auth):
  File "/app/data/atc_data/scripts/datautils.py", line 328, in push_to_confluence
    resp = json.loads(response.text)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

hi @yugoslavskiy , had an erorr above creating root page

**Comment by bambukuning** [comment]
hi guys,

Any advise for erorr above, 

Regards

**Comment by bambukuning** [comment]
resolved change python3 version
